services:
  feed_calculator:    
    container_name: feedcalculator_app
    environment:
      NODE_ENV: production
    build: 
      context: .
      dockerfile: ./Dockerfile         
    ports:
      - 3001:3001    
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - webapp



  # app_db:
  #   container_name: mariadb   
  #   image: mariadb:11.4.2-noble
  #   environment:   
  #     - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=no
  #     - MYSQL_DATABASE=feedcalculator
  #     - MYSQL_USER=appuser
  #     - MYSQL_PASSWORD=root123
  #     - MYSQL_ROOT_PASSWORD=root123
  #   ports:
  #     - 3307:3306
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql
  #     - ./backup/backup.sql:/docker-entrypoint-initdb.d/backup.sql
  #   restart: always
  #   networks: 
  #     - appsnetwork

#   app_server:
#     container_name: apache2
#     image: httpd:alpine3.19
#     volumes:
#       - ${PWD}/website:/usr/local/apache2/htdocs
#     ports: 
#       - 8080:80
#     restart: always
#     networks:
#       - appsnetwork

# volumes:
#   mysql_data:
#   backup:

networks:
  webapp:
    driver: bridge
    external: true

