# This is a basic workflow that is manually triggered

name: Linode Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push: 
    branches: [main]

jobs:
  build: 
    runs-on: self-hosted

    steps:
      - uses: action/checkout@main
      - name: Create .env
      - run: echo 'PORT=${{PORT}} > .env
      #- run: echo
