name: Build and deployment on self hosted VPS

on: 
  push:
    branches:
      [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    
    name: Performing lint
    steps:
      - uses: actions/checkout@v4

      - name: Install npm
        run: npm ci
      - name: run lint
        run: npm run lint
  build: 
    need: [lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20, 22 ]

    name: Install node and try build it on LTS and Latest versions
    steps:     
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install npm
        run: npm ci 
      - name: build Next.js project
        run: npm run build
      